field: 6082ab94-81c7-43df-936c-ca4af64122df # Product Text
fieldLayouts:
  5f77a470-a13c-459a-b376-927d5b90c820:
    tabs:
      -
        elements:
          -
            fieldUid: 59951f82-1b43-4636-9472-729069bc8df7 # Basic Lead
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 51531e4e-b696-4edb-b7b7-da517c4f4d08 # Subtitle Level
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  51531e4e-b696-4edb-b7b7-da517c4f4d08: # Subtitle Level
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: subtitleLevel
    instructions: ''
    name: 'Subtitle Level'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - h2
            -
              - value
              - h2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - h3
            -
              - value
              - h3
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - h4
            -
              - value
              - h4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - h5
            -
              - value
              - h5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - h6
            -
              - value
              - h6
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  59951f82-1b43-4636-9472-729069bc8df7: # Basic Lead
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: cellLeadtxt
    instructions: ''
    name: 'Basic Lead'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: mxLead
name: Lead
sortOrder: 3
