field: 6082ab94-81c7-43df-936c-ca4af64122df # Product Text
fieldLayouts:
  396179c1-d526-4f99-a9a6-4eec55f6a530:
    tabs:
      -
        elements:
          -
            fieldUid: 0791dafd-bfd6-4b0f-b189-d162592760b7 # Textbox Div
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0791dafd-bfd6-4b0f-b189-d162592760b7: # Textbox Div
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cellTxtBox
    instructions: ''
    name: 'Textbox Div'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Block Start'
            -
              - value
              - txtBoxStart
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Block End'
            -
              - value
              - txtBoxEnd
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: mxTxtBox
name: 'Text Box'
sortOrder: 5
