fieldLayouts:
  a84cf9ff-089a-4a29-9658-8232593cf062:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 962030ff-b78e-44e8-931f-67e3fbd348e6 # Page Claim
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 8fbaa9c4-de52-411c-b9b7-2d8a02765aaf # Universal SEO Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ddc1a314-5b75-48dd-8397-738ddb51f3c8 # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 350c27ed-b9c7-4a5a-a653-ebac5a807f68 # Shop Listing Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f7d5d311-8bd1-4a2f-a8e5-642d9982779c # Enable Column ?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6082ab94-81c7-43df-936c-ca4af64122df # Product Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
      -
        elements:
          -
            fieldUid: f82acd93-420b-4b5b-8a7e-805ef6d3aea2 # Head Angle 0° / 90°
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6b970296-d52f-465f-9ff7-1efbcf2a12b2 # Theme Switch
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Coordinator
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 30d24b19-5861-4d46-90a2-ec86f8b0efc8 # Subpage SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: hallOfFame
hasTitleField: true
name: 'Hall of Fame'
section: 67d3c7d7-b020-4484-87f5-50b040cab6be # Hall of Fame
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: none
