columnSuffix: null
contentColumnType: text
fieldGroup: 32b6581c-f334-41d2-8c31-56debf8fa7cb # Shop
handle: buyersTrustText
instructions: 'Erscheint auf den Produktseiten unterhalb des Kaufbutton (Ausserhalb der weissen Fläche)'
name: 'Buyers Trust Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Simple.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: language
type: craft\redactor\Field
