columnSuffix: null
contentColumnType: string
fieldGroup: 32b6581c-f334-41d2-8c31-56debf8fa7cb # Shop
handle: catProductSize
instructions: ''
name: 'Produkt Grösse'
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: '1'
  limit: null
  localizeRelations: false
  selectionLabel: 'Produktgrösse hinzufügen'
  showSiteMenu: true
  source: 'group:06080c3e-d173-4c0a-b1be-3b2c86bcf362' # Produktgrösse
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
