columnSuffix: null
contentColumnType: string
fieldGroup: e5bdd4fe-93a8-4915-ab87-93602a94922b # Coordinator
handle: gridWidth
instructions: ''
name: 'Grid Width'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 'Span 1'
        -
          - value
          - span1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Span 2'
        -
          - value
          - span2
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Span 3'
        -
          - value
          - span3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Span 4'
        -
          - value
          - span4
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Span 5'
        -
          - value
          - span5
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Span 6'
        -
          - value
          - span6
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Span 7'
        -
          - value
          - span7
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Span 8'
        -
          - value
          - span8
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Span 9'
        -
          - value
          - span9
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Span 10'
        -
          - value
          - span10
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Span 11'
        -
          - value
          - span11
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Span 12'
        -
          - value
          - span12
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
