columnSuffix: null
contentColumnType: boolean
fieldGroup: 32b6581c-f334-41d2-8c31-56debf8fa7cb # Shop
handle: hallOfFame
instructions: ''
name: 'Hall of Fame'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
