columnSuffix: null
contentColumnType: text
fieldGroup: 8536034c-56a9-4ae8-ac9c-1fde5d3c3313 # Homepage
handle: introText
instructions: ''
name: 'Intro Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
