columnSuffix: null
contentColumnType: text
fieldGroup: 80b6829c-358d-4844-bbaf-990e4006dbe6 # Common
handle: lead
instructions: ''
name: 'Basic Lead'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
