columnSuffix: null
contentColumnType: text
fieldGroup: b561ef0e-3093-459e-ba9a-555511435eb8 # Globals
handle: naviName
instructions: ''
name: 'Navi Name'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: '1'
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
