columnSuffix: null
contentColumnType: string
fieldGroup: b561ef0e-3093-459e-ba9a-555511435eb8 # Globals
handle: naviLinks
instructions: ''
name: 'Navi Links'
searchable: true
settings:
  contentTable: '{{%matrixcontent_navilinks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
