columnSuffix: null
contentColumnType: text
fieldGroup: 21f04442-c9bf-42c3-a5a0-d899ef06f6eb # Pages
handle: pageClaim
instructions: ''
name: 'Page Claim'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
