columnSuffix: null
contentColumnType: text
fieldGroup: 32b6581c-f334-41d2-8c31-56debf8fa7cb # Shop
handle: payrexxTransactionId
instructions: ''
name: 'Payrexx Transaction Id'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
