columnSuffix: null
contentColumnType: string
fieldGroup: e5bdd4fe-93a8-4915-ab87-93602a94922b # Coordinator
handle: positionLower
instructions: ''
name: Positioning
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Top
        -
          - value
          - top
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Bottom
        -
          - value
          - bottom
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
