columnSuffix: null
contentColumnType: string
fieldGroup: 32b6581c-f334-41d2-8c31-56debf8fa7cb # Shop
handle: productText
instructions: ''
name: 'Product Text'
searchable: true
settings:
  contentTable: '{{%matrixcontent_producttext}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
