columnSuffix: null
contentColumnType: string
fieldGroup: d0379430-3004-4eb7-af6d-c137e345363a # SEO
handle: seoImage
instructions: 1200x630
name: 'SEO Image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:f30daf60-565d-4952-a03a-5740ee091724'
  defaultUploadLocationSubpath: '{slug}'
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add SEO Image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:f30daf60-565d-4952-a03a-5740ee091724'
  singleUploadLocationSubpath: '{slug}'
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
