columnSuffix: null
contentColumnType: string
fieldGroup: 32b6581c-f334-41d2-8c31-56debf8fa7cb # Shop
handle: variantThumb
instructions: ''
name: 'Variant Thumb'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:c7817451-af61-4d42-af4a-fb7370ef4fd2' # Shop
  defaultUploadLocationSubpath: '{slug}'
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Produktbild hinzufügen'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:c7817451-af61-4d42-af4a-fb7370ef4fd2' # Shop
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:c7817451-af61-4d42-af4a-fb7370ef4fd2' # Shop
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
