field: 8b8cae1e-f369-4549-841b-83cd0c74531e # Grid Coordinator
fieldLayouts:
  de097a91-2328-41f4-87ff-f4451052f447:
    tabs:
      -
        elements:
          -
            fieldUid: bd1b86cc-8c8a-443d-8dd6-7b20a69f6862 # Grid Width
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 025fe7fb-2982-4476-99c0-3f43ab0501b3 # Grid Height
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b0476a59-9c5e-494a-8c8f-c55c61c0be59 # Grid Offset
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ead47a90-a89e-4ae0-9c7f-36ee9f0ef41d # No Mobile
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c7588676-6e6a-4430-869f-c3b5656247c4 # H?
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  025fe7fb-2982-4476-99c0-3f43ab0501b3: # Grid Height
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: gridHeight
    instructions: ''
    name: 'Grid Height'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Span 1'
            -
              - value
              - span1
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Span 2'
            -
              - value
              - span2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 3'
            -
              - value
              - span3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 4'
            -
              - value
              - span4
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  b0476a59-9c5e-494a-8c8f-c55c61c0be59: # Grid Offset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: gridOffset
    instructions: ''
    name: 'Grid Offset'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Offset 0'
            -
              - value
              - offset0
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Offset 1'
            -
              - value
              - offset1
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 2'
            -
              - value
              - offset2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 3'
            -
              - value
              - offset3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 4'
            -
              - value
              - offset4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 5'
            -
              - value
              - offset5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 6'
            -
              - value
              - offset6
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 7'
            -
              - value
              - offset7
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 8'
            -
              - value
              - offset8
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 9'
            -
              - value
              - offset9
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 10'
            -
              - value
              - offset10
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 11'
            -
              - value
              - offset11
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 12'
            -
              - value
              - offset12
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  bd1b86cc-8c8a-443d-8dd6-7b20a69f6862: # Grid Width
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: gridWidth
    instructions: ''
    name: 'Grid Width'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Span 1'
            -
              - value
              - span1
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Span 2'
            -
              - value
              - span2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 3'
            -
              - value
              - span3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 4'
            -
              - value
              - span4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 5'
            -
              - value
              - span5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 6'
            -
              - value
              - span6
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 7'
            -
              - value
              - span7
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 8'
            -
              - value
              - span8
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 9'
            -
              - value
              - span9
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 10'
            -
              - value
              - span10
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 11'
            -
              - value
              - span11
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 12'
            -
              - value
              - span12
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c7588676-6e6a-4430-869f-c3b5656247c4: # H?
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: subtitleLevel
    instructions: ''
    name: 'H?'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - H2
            -
              - value
              - h2
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - H3
            -
              - value
              - h3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H4
            -
              - value
              - h4
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  ead47a90-a89e-4ae0-9c7f-36ee9f0ef41d: # No Mobile
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: hideOnMobile
    instructions: ''
    name: 'No Mobile'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
