field: fd9400a9-9273-4056-9ab6-c1002f1bba94 # Grid Coordinator
fieldLayouts:
  151124e1-39cf-44c1-a601-7471a3c8cb99:
    tabs:
      -
        elements:
          -
            fieldUid: 4c5fa2af-1c12-45fb-868f-ee3d6b6cf21a # Grid Width
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c7861ec0-d436-4b74-b5f7-7cb5042b2647 # Grid Height
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f43126d1-9b2d-4f76-99c8-f6b2b929dc5c # Grid Offset
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7b17e818-42bf-4627-b500-ba29e3ce9049 # Autoplay?
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 89953990-3fda-43a6-a581-7f0f5b4dcb0c # No Mobile
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4c5fa2af-1c12-45fb-868f-ee3d6b6cf21a: # Grid Width
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: gridWidth
    instructions: ''
    name: 'Grid Width'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Span 1'
            -
              - value
              - span1
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Span 2'
            -
              - value
              - span2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 3'
            -
              - value
              - span3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 4'
            -
              - value
              - span4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 5'
            -
              - value
              - span5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 6'
            -
              - value
              - span6
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 7'
            -
              - value
              - span7
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 8'
            -
              - value
              - span8
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 9'
            -
              - value
              - span9
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 10'
            -
              - value
              - span10
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 11'
            -
              - value
              - span11
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 12'
            -
              - value
              - span12
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  7b17e818-42bf-4627-b500-ba29e3ce9049: # Autoplay?
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: autoplay
    instructions: ''
    name: 'Autoplay?'
    searchable: true
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  89953990-3fda-43a6-a581-7f0f5b4dcb0c: # No Mobile
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: hideOnMobile
    instructions: ''
    name: 'No Mobile'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  c7861ec0-d436-4b74-b5f7-7cb5042b2647: # Grid Height
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: gridHeight
    instructions: ''
    name: 'Grid Height'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Span 1'
            -
              - value
              - span1
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Span 2'
            -
              - value
              - span2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 3'
            -
              - value
              - span3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Span 4'
            -
              - value
              - span4
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f43126d1-9b2d-4f76-99c8-f6b2b929dc5c: # Grid Offset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: gridOffset
    instructions: ''
    name: 'Grid Offset'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Offset 0'
            -
              - value
              - offset0
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Offset 1'
            -
              - value
              - offset1
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 2'
            -
              - value
              - offset2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 3'
            -
              - value
              - offset3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 4'
            -
              - value
              - offset4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 5'
            -
              - value
              - offset5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 6'
            -
              - value
              - offset6
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 7'
            -
              - value
              - offset7
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 8'
            -
              - value
              - offset8
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 9'
            -
              - value
              - offset9
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 10'
            -
              - value
              - offset10
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 11'
            -
              - value
              - offset11
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Offset 12'
            -
              - value
              - offset12
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
