defaultPlacement: end
enableVersioning: true
handle: microNews
name: 'Micro News'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  bc63c03e-bdb9-4257-848b-bea06f5ce825: # Kaspar Allenbach
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  cb7c4cc1-6fcf-4482-912c-87ce9bbe5d98: # Kaspar Allenbach en
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
